# Generated by Django 4.0 on 2021-12-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='course',
            new_name='Курс',
        ),
    ]
