# Generated by Django 4.0 on 2021-12-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_course_group_курс'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Курс',
            new_name='course',
        ),
    ]
